version: '3.1'
services:
#  db:
#    image: postgres:10-alpine
#    ports:
#      - "5432:5432"
#    environment:
#      POSTGRES_USER: user1
#      POSTGRES_PASSWORD: changeme
#      POSTGRES_DB: tododb
#  admin:
#    image: adminer
#    restart: always
#    depends_on:
#      - db
#    ports:
#      - 8080:8080
  mysql-tracking:
      image: mysql
      ports:
        - "3307:3306"
      environment:
        - MYSQL_DATABASE=dbname # Change {{db-name}}
        - MYSQL_ROOT_PASSWORD=db-pass # Change {{root-password}}
      restart: always
